version: "3.6"
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  mysql:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rpassword'
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssw0rd'
  mongodb:
    image: mongo:4.4.0-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    image: redis:6.0.6
    ports:
      - "6379:6379"